DROP TABLE IF EXISTS ADDR_MASTER CASCADE;
DROP SEQUENCE IF EXISTS SEQ_ADDR_MASTER;

DROP TABLE IF EXISTS USER_MASTER CASCADE;
DROP SEQUENCE IF EXISTS SEQ_USER_MASTER;

DROP TABLE IF EXISTS RECIPIENT_MASTER CASCADE;
DROP SEQUENCE IF EXISTS SEQ_RECIPIENT_MASTER;

CREATE SEQUENCE SEQ_USER_MASTER MINVALUE 1 INCREMENT BY 1 MAXVALUE 2147483647;
CREATE TABLE USER_MASTER (
    USER_ID INTEGER NOT NULL DEFAULT NEXTVAL('SEQ_USER_MASTER'),
    EXT_USER_ID UUID NOT NULL DEFAULT gen_random_uuid(),
    LINE_USER_ID VARCHAR(33) NOT NULL,
    CONSTRAINT USRM_USER_ID_PK PRIMARY KEY (USER_ID),
    CONSTRAINT USRM_EXT_USER_ID_UK UNIQUE (EXT_USER_ID)
);

CREATE SEQUENCE SEQ_RECIPIENT_MASTER MINVALUE 1 INCREMENT BY 1 MAXVALUE 2147483647;
CREATE TABLE RECIPIENT_MASTER (
    RECIPIENT_ID INTEGER NOT NULL DEFAULT NEXTVAL('SEQ_RECIPIENT_MASTER'),
    EXT_RECIPIENT_ID UUID NOT NULL DEFAULT gen_random_uuid(),
    RECIPIENT_TYPE INTEGER DEFAULT 0 NOT NULL,
    LINE_RECIPIENT_ID VARCHAR(33) NOT NULL,
    RECIPIENT_DESCRIPTION VARCHAR(64) DEFAULT '',
    CONSTRAINT RCPM_RECIPIENT_ID_PK PRIMARY KEY (RECIPIENT_ID),
    CONSTRAINT RCPM_EXT_RECIPIENT_ID_UK UNIQUE (EXT_RECIPIENT_ID)
);

CREATE SEQUENCE SEQ_ADDR_MASTER MINVALUE 20 INCREMENT BY 1 MAXVALUE 2147483647;
CREATE TABLE ADDR_MASTER (
    ADDR_ID INTEGER NOT NULL DEFAULT NEXTVAL('SEQ_ADDR_MASTER'),
    EXT_ADDR_ID UUID NOT NULL DEFAULT gen_random_uuid(),
    ADDR_MAIL VARCHAR(64) NOT NULL,
    USER_ID INTEGER NOT NULL,
    RECIPIENT_ID INTEGER NOT NULL,
    STATUS INTEGER DEFAULT 0 NOT NULL,
    CONSTRAINT ADRM_ADDR_ID_PK PRIMARY KEY (ADDR_ID),
    CONSTRAINT ADRM_ADDR_MAIL_UK UNIQUE (ADDR_MAIL),
    CONSTRAINT ADRM_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USER_MASTER(USER_ID),
    CONSTRAINT ADRM_EXT_USER_ID_UK UNIQUE (EXT_ADDR_ID),
    CONSTRAINT ADRM_RECIPIENT_ID_FK FOREIGN KEY (RECIPIENT_ID) REFERENCES RECIPIENT_MASTER(RECIPIENT_ID)
);

-- default user and group
INSERT INTO USER_MASTER (USER_ID,LINE_USER_ID) VALUES (0,'');
INSERT INTO RECIPIENT_MASTER (RECIPIENT_ID,RECIPIENT_TYPE,LINE_RECIPIENT_ID) VALUES (0,0,'');
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,RECIPIENT_ID,STATUS) VALUES (0, 'default', 0, 0, 0);

-- RFC 2142
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,RECIPIENT_ID,STATUS) VALUES (1, 'info', 0, 0, 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,RECIPIENT_ID,STATUS) VALUES (2, 'marketing', 0, 0, 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,RECIPIENT_ID,STATUS) VALUES (3, 'sales', 0, 0, 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,RECIPIENT_ID,STATUS) VALUES (4, 'support', 0, 0, 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,RECIPIENT_ID,STATUS) VALUES (5, 'abuse', 0, 0, 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,RECIPIENT_ID,STATUS) VALUES (6, 'noc', 0, 0, 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,RECIPIENT_ID,STATUS) VALUES (7, 'security', 0, 0, 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,RECIPIENT_ID,STATUS) VALUES (8, 'postmaster', 0, 0, 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,RECIPIENT_ID,STATUS) VALUES (9, 'hostmaster', 0, 0, 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,RECIPIENT_ID,STATUS) VALUES (10, 'usenet', 0, 0, 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,RECIPIENT_ID,STATUS) VALUES (11, 'news', 0, 0, 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,RECIPIENT_ID,STATUS) VALUES (12, 'webmaster', 0, 0, 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,RECIPIENT_ID,STATUS) VALUES (13, 'www', 0, 0, 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,RECIPIENT_ID,STATUS) VALUES (14, 'uucp', 0, 0, 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,RECIPIENT_ID,STATUS) VALUES (15, 'ftp', 0, 0, 0);
-- operating system user
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,RECIPIENT_ID,STATUS) VALUES (16, 'root', 0, 0, 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,RECIPIENT_ID,STATUS) VALUES (17, 'toor', 0, 0, 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,RECIPIENT_ID,STATUS) VALUES (18, 'admin', 0, 0, 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,RECIPIENT_ID,STATUS) VALUES (19, 'administrator', 0, 0, 0);

COMMIT;