DROP TABLE IF EXISTS ADDR_MASTER CASCADE;
DROP SEQUENCE IF EXISTS SEQ_ADDR_MASTER;

DROP TABLE IF EXISTS USER_MASTER CASCADE;
DROP SEQUENCE IF EXISTS SEQ_USER_MASTER;

CREATE TABLE USER_MASTER (
    USER_ID INTEGER NOT NULL,
    LINE_USER_ID VARCHAR(33) NOT NULL,
    CONSTRAINT USRM_USER_ID_PK PRIMARY KEY (USER_ID)
);
CREATE SEQUENCE SEQ_USER_MASTER MINVALUE 1 INCREMENT BY 1 MAXVALUE 2147483647;

CREATE TABLE ADDR_MASTER (
    ADDR_ID INTEGER NOT NULL,
    ADDR_MAIL VARCHAR(64) NOT NULL,
    USER_ID INTEGER NOT NULL,
    NOTIFY_TOKEN VARCHAR(43) NOT NULL,
    STATUS INTEGER DEFAULT 0 NOT NULL,
    CONSTRAINT ADRM_ADDR_ID_PK PRIMARY KEY (ADDR_ID),
    CONSTRAINT ADRM_ADDR_MAIL_UK UNIQUE (ADDR_MAIL),
    CONSTRAINT ADRM_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USER_MASTER(USER_ID)
);
CREATE SEQUENCE SEQ_ADDR_MASTER MINVALUE 20 INCREMENT BY 1 MAXVALUE 2147483647;

-- default user
INSERT INTO USER_MASTER (USER_ID,LINE_USER_ID) VALUES (0,'');
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,NOTIFY_TOKEN,STATUS) VALUES (0, 'default', 0, '', 0);

-- RFC 2142
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,NOTIFY_TOKEN,STATUS) VALUES (1, 'info', 0, '', 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,NOTIFY_TOKEN,STATUS) VALUES (2, 'marketing', 0, '', 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,NOTIFY_TOKEN,STATUS) VALUES (3, 'sales', 0, '', 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,NOTIFY_TOKEN,STATUS) VALUES (4, 'support', 0, '', 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,NOTIFY_TOKEN,STATUS) VALUES (5, 'abuse', 0, '', 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,NOTIFY_TOKEN,STATUS) VALUES (6, 'noc', 0, '', 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,NOTIFY_TOKEN,STATUS) VALUES (7, 'security', 0, '', 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,NOTIFY_TOKEN,STATUS) VALUES (8, 'postmaster', 0, '', 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,NOTIFY_TOKEN,STATUS) VALUES (9, 'hostmaster', 0, '', 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,NOTIFY_TOKEN,STATUS) VALUES (10, 'usenet', 0, '', 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,NOTIFY_TOKEN,STATUS) VALUES (11, 'news', 0, '', 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,NOTIFY_TOKEN,STATUS) VALUES (12, 'webmaster', 0, '', 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,NOTIFY_TOKEN,STATUS) VALUES (13, 'www', 0, '', 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,NOTIFY_TOKEN,STATUS) VALUES (14, 'uucp', 0, '', 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,NOTIFY_TOKEN,STATUS) VALUES (15, 'ftp', 0, '', 0);
-- operating system user
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,NOTIFY_TOKEN,STATUS) VALUES (16, 'root', 0, '', 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,NOTIFY_TOKEN,STATUS) VALUES (17, 'toor', 0, '', 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,NOTIFY_TOKEN,STATUS) VALUES (18, 'admin', 0, '', 0);
INSERT INTO ADDR_MASTER (ADDR_ID,ADDR_MAIL,USER_ID,NOTIFY_TOKEN,STATUS) VALUES (19, 'administrator', 0, '', 0);

COMMIT;